name: MLOps Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest
    env:
      MODEL_PATH: ./model.pkl
      API_KEY: ${{ secrets.API_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate test data
        run: python generate_test_data.py

      - name: Train realistic model
        run: python create_realistic_model.py

      - name: Validate and Deploy Model
        run: python model_deployment.py --env production
